'use client';
import Link from 'next/link';
import {Activity, ArrowRight, BarChart3, CheckCircle2, FileSpreadsheet, Globe2, LayoutDashboard, LogOut, Mail, MapPin, Settings, ShieldCheck, Sparkles, Target, Upload, Users, Zap} from 'lucide-react';
import {Badge} from '@/components/ui/badge';
import {Button} from '@/components/ui/button';
import {Progress} from '@/components/ui/progress';

const nav=[
  ['Overview','/workspace',LayoutDashboard],['Upload & filter','/domain-filter',FileSpreadsheet],['Domain discovery','/domain-hunter',Globe2],['Qualified leads','/domain-filter',Target],['Prospects','/domain-filter',Users],['Campaigns','/super-admin',Mail],['Settings','/domain-hunter/settings',Settings],['Audit & access','/super-admin',ShieldCheck],
] as const;
const stats=[
  ['Active datasets','04','Current uploads',FileSpreadsheet,'text-sky-700','bg-sky-50'],
  ['Qualified leads','724','No website detected',Target,'text-emerald-700','bg-emerald-50'],
  ['Prospects','186','Ready for outreach',Users,'text-violet-700','bg-violet-50'],
  ['Campaign sent','1,248','98.4% delivered',Mail,'text-orange-700','bg-orange-50'],
] as const;
const steps=[
  ['Upload domain data','Import CSV/XLSX as a fresh dataset or merge it with active uploads.','/domain-filter',Upload],
  ['Filter and qualify','Remove duplicates, exclude privacy records and process only selected countries.','/domain-filter',Sparkles],
  ['Approve prospects','Review contact and location data, then move selected leads to Prospects.','/domain-filter',CheckCircle2],
  ['Start outreach','Create personalized HTML email campaigns with safe random sending delays.','/super-admin',Mail],
] as const;

export function VyavasWorkspace({user}:{user?:{displayName:string;email:string}}){
  return <div className="min-h-screen bg-[#f3f7fb] text-[#142237]">
    <aside className="fixed inset-y-0 left-0 z-30 hidden w-64 flex-col bg-[#091b30] text-slate-300 lg:flex">
      <div className="flex h-20 items-center gap-3 border-b border-white/10 px-6"><span className="grid size-10 place-items-center rounded-xl bg-[#50e3b2] text-[#071a2e]"><Zap className="size-5"/></span><div><div className="text-lg font-black tracking-[.16em] text-white">VYAVAS</div><div className="text-[11px] uppercase tracking-[.18em] text-slate-500">Growth OS</div></div></div>
      <nav className="flex-1 space-y-1 px-3 py-5" aria-label="Main navigation">{nav.map(([label,href,Icon],i)=><Link key={label} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${i===0?'bg-white/10 text-white shadow-[inset_3px_0_0_#50e3b2]':'hover:bg-white/5 hover:text-white'}`}><Icon className="size-[18px]"/>{label}</Link>)}</nav>
      <div className="m-4 rounded-2xl border border-white/10 bg-white/[.04] p-4"><div className="flex items-center gap-2 text-sm font-semibold text-white"><ShieldCheck className="size-4 text-[#50e3b2]"/>Production controls</div><p className="mt-2 text-xs leading-5 text-slate-500">Role access, audit history, duplicate protection and sending limits are enabled.</p></div>
    </aside>
    <main className="min-h-screen lg:pl-64">
      <header className="sticky top-0 z-20 flex min-h-20 items-center justify-between border-b border-slate-200/80 bg-white/90 px-5 backdrop-blur-xl sm:px-8"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-slate-400">Operations workspace</p><h1 className="mt-1 text-xl font-bold">Lead acquisition overview</h1></div><div className="flex items-center gap-3"><Badge className="hidden bg-emerald-50 text-emerald-700 xl:inline-flex"><span className="mr-2 size-2 rounded-full bg-emerald-500"/>All systems ready</Badge>{user&&<div className="hidden text-right md:block"><div className="max-w-48 truncate text-sm font-semibold">{user.displayName}</div><div className="max-w-48 truncate text-xs text-slate-400">{user.email}</div></div>}<Link href="/domain-filter"><Button className="bg-[#0b223b] hover:bg-[#153b5f]"><Upload className="mr-2 size-4"/>Upload file</Button></Link><a href="/signout-with-chatgpt?return_to=%2F" target="_top" aria-label="Log out"><Button variant="outline" size="icon"><LogOut className="size-4"/></Button></a></div></header>
      <div className="mx-auto max-w-[1500px] space-y-6 p-5 sm:p-8">
        <section className="overflow-hidden rounded-3xl bg-[#0b223b] p-6 text-white shadow-xl shadow-slate-900/10 sm:p-8"><div className="grid items-center gap-8 xl:grid-cols-[1fr_480px]"><div><Badge className="bg-[#50e3b2]/15 text-[#79f0c8]">Domain-to-prospect pipeline</Badge><h2 className="mt-4 max-w-2xl text-3xl font-bold tracking-tight sm:text-4xl">Find businesses that registered a domain but still need a website.</h2><p className="mt-4 max-w-2xl text-base leading-7 text-slate-300">Upload registration data, process selected countries, remove duplicate or protected contacts, and move only qualified no-website leads into outreach.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/domain-filter"><Button className="bg-[#50e3b2] text-[#082036] hover:bg-[#70ebc4]">Start filtering<ArrowRight className="ml-2 size-4"/></Button></Link><Link href="/domain-hunter"><Button variant="outline" className="border-white/20 bg-white/5 text-white hover:bg-white/10 hover:text-white">Discover domains by date</Button></Link></div></div><div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><div className="flex items-center justify-between text-sm"><span className="font-semibold">Today&apos;s pipeline</span><span className="font-mono text-[#79f0c8]">67% complete</span></div><Progress value={67} className="mt-4 h-2"/><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-white/[.06] p-3"><div className="text-slate-400">Checked</div><b className="mt-1 block text-xl">2,647</b></div><div className="rounded-xl bg-white/[.06] p-3"><div className="text-slate-400">Qualified</div><b className="mt-1 block text-xl text-[#79f0c8]">724</b></div><div className="rounded-xl bg-white/[.06] p-3"><div className="text-slate-400">Duplicates</div><b className="mt-1 block text-xl">118</b></div><div className="rounded-xl bg-white/[.06] p-3"><div className="text-slate-400">Live rejected</div><b className="mt-1 block text-xl">1,005</b></div></div></div></div></section>
        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label,value,note,Icon,tone,bg])=><article key={label} className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div><span className={`grid size-11 place-items-center rounded-xl ${bg}`}><Icon className={`size-5 ${tone}`}/></span></div><p className="mt-3 text-xs text-slate-400">{note}</p></article>)}</section>
        <section className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="rounded-2xl border border-slate-200/80 bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Complete workflow</h2><p className="mt-1 text-sm text-slate-500">Every step is connected and saved.</p></div><BarChart3 className="size-5 text-slate-400"/></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{steps.map(([title,desc,href,Icon],i)=><Link href={href} key={title} className="group rounded-2xl border border-slate-200 p-4 transition hover:border-emerald-300 hover:shadow-md"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-600 group-hover:bg-emerald-50 group-hover:text-emerald-700"><Icon className="size-5"/></span><div><div className="text-xs font-bold text-slate-400">STEP {i+1}</div><h3 className="mt-1 font-bold">{title}</h3><p className="mt-1 text-sm leading-5 text-slate-500">{desc}</p></div></div></Link>)}</div></div><aside className="rounded-2xl border border-slate-200/80 bg-white p-6"><div className="flex items-center gap-2"><Activity className="size-5 text-emerald-600"/><h2 className="text-lg font-bold">Recent activity</h2></div><div className="mt-5 space-y-5">{[['India dataset processed','724 qualified leads','2 min ago'],['Duplicates removed','118 records eliminated','18 min ago'],['Prospects updated','42 leads moved','Today, 11:40'],['Campaign paused safely','No queued mail lost','Yesterday']].map(([a,b,c])=><div key={a} className="relative border-l-2 border-slate-100 pl-4"><span className="absolute -left-[5px] top-1 size-2 rounded-full bg-emerald-500"/><div className="text-sm font-semibold">{a}</div><div className="mt-0.5 text-xs text-slate-500">{b}</div><div className="mt-1 text-[11px] text-slate-400">{c}</div></div>)}</div><Link href="/super-admin" className="mt-6 flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3 text-sm font-semibold hover:bg-slate-100">View audit and access<ArrowRight className="size-4"/></Link></aside></section>
        <section className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><MapPin className="size-5 text-sky-600"/><h3 className="mt-3 font-bold">Country & location insights</h3><p className="mt-2 text-sm leading-6 text-slate-500">Compare qualified leads by country, state, city and pincode.</p></div><div className="rounded-2xl border bg-white p-5"><ShieldCheck className="size-5 text-emerald-600"/><h3 className="mt-3 font-bold">Clean prospect data</h3><p className="mt-2 text-sm leading-6 text-slate-500">Free personal emails only, privacy contacts blocked and exclusions remembered.</p></div><div className="rounded-2xl border bg-white p-5"><Mail className="size-5 text-orange-600"/><h3 className="mt-3 font-bold">Safe outreach queue</h3><p className="mt-2 text-sm leading-6 text-slate-500">HTML variables, SMTP controls, random delay, pause and sending caps.</p></div></section>
      </div>
    </main>
  </div>
}
